spring:
  application:
    name: books-api

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:books}
    username: ${DB_USER:books_user}
    password: ${DB_PASSWORD:books_password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

server:
  port: ${APP_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "when_authorized"

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: ${JWT_SECRET:dev-secret-key-for-jwt-token-generation-2024-must-be-at-least-32-characters-long}